# platform :ios, "8.0"
# use_frameworks!


target 'drawApp' do
 # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
 use_frameworks!

 # Pods for drawApp
 pod 'Starscream', :git => 'https://github.com/daltoniam/Starscream', :branch => 'swift3'

end
